services:
  - type: web
    name: proyecto-final
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2
